function Nx250Ny100ellx10k10000 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NX250NY100ELLX10K10000 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  NX250NY100ELLX10K10000 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Nx250Ny100ellx10k10000 = importfile("/home/ida/Documents/GitHub/FEniCS/Phase_Field_Fracture/Test_ellx_change/Nx_250_Ny_100_ellx_10_k_10000.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Feb-2021 10:49:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Damage", "Displacement0", "Displacement1", "Displacement2", "F33", "J", "Pressure", "NominalStress0", "NominalStress1", "NominalStress2", "NominalStress3", "NominalStress4", "NominalStress5", "NominalStress6", "NominalStress7", "NominalStress8", "vtkValidPointMask", "arc_length", "Points0", "Points1", "Points2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Nx250Ny100ellx10k10000 = readtable(filename, opts);

end