function Nx250Ny100ellx10k10 = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  NX250NY100ELLX10K10 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  NX250NY100ELLX10K10 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Nx250Ny100ellx10k10 = importfile1("/home/ida/Documents/GitHub/FEniCS/Phase_Field_Fracture/StressProfilePlaneStrain/Nx_250_Ny_100_ellx_10_k_10.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Feb-2021 16:07:51

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Damage", "Displacement0", "Displacement1", "Displacement2", "Pressure", "NominalStress0", "NominalStress1", "NominalStress2", "NominalStress3", "NominalStress4", "NominalStress5", "NominalStress6", "NominalStress7", "NominalStress8", "vtkValidPointMask", "arc_length", "Points0", "Points1", "Points2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Nx250Ny100ellx10k10 = readtable(filename, opts);

end