# -*- coding: utf-8 -*-
from __future__ import division
import numpy as np
import quadpy
import matplotlib.pyplot as plt
import ctypes as c
import multiprocessing as mp
from pynverse import inversefunc
import gen_var

cauchy_11_eq_strain_P_tilde_modLog101_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog101_lebedev_021.npy')
cauchy_11_eq_strain_P_tilde_modLog102_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog102_lebedev_021.npy')
cauchy_11_eq_strain_P_tilde_modLog103_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog103_lebedev_021.npy')
cauchy_11_eq_strain_P_tilde_modLog104_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog104_lebedev_021.npy')
cauchy_11_eq_strain_P_tilde_modLog105_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog105_lebedev_021.npy')

cauchy_11_eq_strain_P_tilde_modLog101_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog101_lebedev_041.npy')
cauchy_11_eq_strain_P_tilde_modLog102_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog102_lebedev_041.npy')
cauchy_11_eq_strain_P_tilde_modLog103_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog103_lebedev_041.npy')
cauchy_11_eq_strain_P_tilde_modLog104_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog104_lebedev_041.npy')
cauchy_11_eq_strain_P_tilde_modLog105_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog105_lebedev_041.npy')

cauchy_11_eq_strain_P_tilde_modLog101_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog101_lebedev_059.npy')
cauchy_11_eq_strain_P_tilde_modLog102_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog102_lebedev_059.npy')
cauchy_11_eq_strain_P_tilde_modLog103_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog103_lebedev_059.npy')
cauchy_11_eq_strain_P_tilde_modLog104_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog104_lebedev_059.npy')
cauchy_11_eq_strain_P_tilde_modLog105_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog105_lebedev_059.npy')

cauchy_11_eq_strain_P_tilde_modLog101_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog101_lebedev_071.npy')
cauchy_11_eq_strain_P_tilde_modLog102_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog102_lebedev_071.npy')
cauchy_11_eq_strain_P_tilde_modLog103_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog103_lebedev_071.npy')
cauchy_11_eq_strain_P_tilde_modLog104_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog104_lebedev_071.npy')
cauchy_11_eq_strain_P_tilde_modLog105_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog105_lebedev_071.npy')

cauchy_11_eq_strain_P_tilde_modLog101_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog101_lebedev_095.npy')
cauchy_11_eq_strain_P_tilde_modLog102_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog102_lebedev_095.npy')
cauchy_11_eq_strain_P_tilde_modLog103_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog103_lebedev_095.npy')
cauchy_11_eq_strain_P_tilde_modLog104_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog104_lebedev_095.npy')
cauchy_11_eq_strain_P_tilde_modLog105_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog105_lebedev_095.npy')

cauchy_11_eq_strain_P_tilde_modLog101_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog101_lebedev_113.npy')
cauchy_11_eq_strain_P_tilde_modLog102_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog102_lebedev_113.npy')
cauchy_11_eq_strain_P_tilde_modLog103_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog103_lebedev_113.npy')
cauchy_11_eq_strain_P_tilde_modLog104_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog104_lebedev_113.npy')
cauchy_11_eq_strain_P_tilde_modLog105_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog105_lebedev_113.npy')

cauchy_11_eq_strain_P_tilde_modLog101_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog101_lebedev_131.npy')
cauchy_11_eq_strain_P_tilde_modLog102_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog102_lebedev_131.npy')
cauchy_11_eq_strain_P_tilde_modLog103_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog103_lebedev_131.npy')
cauchy_11_eq_strain_P_tilde_modLog104_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog104_lebedev_131.npy')
cauchy_11_eq_strain_P_tilde_modLog105_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_strain_P_tilde_modLog105_lebedev_131.npy')

cauchy_11_eq_force_P_tilde_modLog101_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog101_lebedev_021.npy')
cauchy_11_eq_force_P_tilde_modLog102_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog102_lebedev_021.npy')
cauchy_11_eq_force_P_tilde_modLog103_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog103_lebedev_021.npy')
cauchy_11_eq_force_P_tilde_modLog104_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog104_lebedev_021.npy')
cauchy_11_eq_force_P_tilde_modLog105_lebedev_021 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog105_lebedev_021.npy')

cauchy_11_eq_force_P_tilde_modLog101_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog101_lebedev_041.npy')
cauchy_11_eq_force_P_tilde_modLog102_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog102_lebedev_041.npy')
cauchy_11_eq_force_P_tilde_modLog103_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog103_lebedev_041.npy')
cauchy_11_eq_force_P_tilde_modLog104_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog104_lebedev_041.npy')
cauchy_11_eq_force_P_tilde_modLog105_lebedev_041 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog105_lebedev_041.npy')

cauchy_11_eq_force_P_tilde_modLog101_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog101_lebedev_059.npy')
cauchy_11_eq_force_P_tilde_modLog102_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog102_lebedev_059.npy')
cauchy_11_eq_force_P_tilde_modLog103_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog103_lebedev_059.npy')
cauchy_11_eq_force_P_tilde_modLog104_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog104_lebedev_059.npy')
cauchy_11_eq_force_P_tilde_modLog105_lebedev_059 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog105_lebedev_059.npy')

cauchy_11_eq_force_P_tilde_modLog101_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog101_lebedev_071.npy')
cauchy_11_eq_force_P_tilde_modLog102_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog102_lebedev_071.npy')
cauchy_11_eq_force_P_tilde_modLog103_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog103_lebedev_071.npy')
cauchy_11_eq_force_P_tilde_modLog104_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog104_lebedev_071.npy')
cauchy_11_eq_force_P_tilde_modLog105_lebedev_071 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog105_lebedev_071.npy')

cauchy_11_eq_force_P_tilde_modLog101_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog101_lebedev_095.npy')
cauchy_11_eq_force_P_tilde_modLog102_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog102_lebedev_095.npy')
cauchy_11_eq_force_P_tilde_modLog103_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog103_lebedev_095.npy')
cauchy_11_eq_force_P_tilde_modLog104_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog104_lebedev_095.npy')
cauchy_11_eq_force_P_tilde_modLog105_lebedev_095 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog105_lebedev_095.npy')

cauchy_11_eq_force_P_tilde_modLog101_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog101_lebedev_113.npy')
cauchy_11_eq_force_P_tilde_modLog102_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog102_lebedev_113.npy')
cauchy_11_eq_force_P_tilde_modLog103_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog103_lebedev_113.npy')
cauchy_11_eq_force_P_tilde_modLog104_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog104_lebedev_113.npy')
cauchy_11_eq_force_P_tilde_modLog105_lebedev_113 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog105_lebedev_113.npy')

cauchy_11_eq_force_P_tilde_modLog101_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog101_lebedev_131.npy')
cauchy_11_eq_force_P_tilde_modLog102_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog102_lebedev_131.npy')
cauchy_11_eq_force_P_tilde_modLog103_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog103_lebedev_131.npy')
cauchy_11_eq_force_P_tilde_modLog104_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog104_lebedev_131.npy')
cauchy_11_eq_force_P_tilde_modLog105_lebedev_131 = np.load('/home/jmulderrig/github/research/projects/polymerDamageModel/isakovChainLengthDistributions/cauchy_11_eq_force_P_tilde_modLog105_lebedev_131.npy')

plt.figure(0)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog101_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog101_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog101_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog101_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog101_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog101_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog101_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal strain model UTT - lambda_b_crit = 1.01 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_strain_P_tilde_modLog101_N45.pdf', transparent=True)
plt.close()

plt.figure(1)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog102_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog102_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog102_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog102_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog102_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog102_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog102_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal strain model UTT - lambda_b_crit = 1.02 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_strain_P_tilde_modLog102_N45.pdf', transparent=True)
plt.close()

plt.figure(2)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog103_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog103_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog103_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog103_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog103_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog103_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog103_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal strain model UTT - lambda_b_crit = 1.03 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_strain_P_tilde_modLog103_N45.pdf', transparent=True)
plt.close()

plt.figure(3)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog104_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog104_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog104_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog104_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog104_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog104_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog104_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal strain model UTT - lambda_b_crit = 1.04 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_strain_P_tilde_modLog104_N45.pdf', transparent=True)
plt.close()

plt.figure(4)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog105_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog105_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog105_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog105_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog105_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog105_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_strain, cauchy_11_eq_strain_P_tilde_modLog105_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal strain model UTT - lambda_b_crit = 1.05 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_strain_P_tilde_modLog105_N45.pdf', transparent=True)
plt.close()

plt.figure(5)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog101_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog101_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog101_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog101_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog101_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog101_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog101_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal force model UTT - lambda_b_crit = 1.01 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_force_P_tilde_modLog101_N45.pdf', transparent=True)
plt.close()

plt.figure(6)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog102_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog102_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog102_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog102_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog102_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog102_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog102_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal force model UTT - lambda_b_crit = 1.02 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_force_P_tilde_modLog102_N45.pdf', transparent=True)
plt.close()

plt.figure(7)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog103_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog103_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog103_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog103_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog103_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog103_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog103_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal force model UTT - lambda_b_crit = 1.03 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_force_P_tilde_modLog103_N45.pdf', transparent=True)
plt.close()

plt.figure(8)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog104_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog104_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog104_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog104_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog104_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog104_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog104_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal force model UTT - lambda_b_crit = 1.04 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_force_P_tilde_modLog104_N45.pdf', transparent=True)
plt.close()

plt.figure(9)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog105_lebedev_021[:,3], '-', color='black', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog105_lebedev_041[:,3], '-', color='blue', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog105_lebedev_059[:,3], '-', color='green', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog105_lebedev_071[:,3], '-', color='red', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog105_lebedev_095[:,3], '-', color='orange', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog105_lebedev_113[:,3], '-', color='cyan', linewidth=0.75)
plt.plot(gen_var.lmbda_steps_eq_force, cauchy_11_eq_force_P_tilde_modLog105_lebedev_131[:,3], '-', color='magenta', linewidth=0.75)
plt.legend(['21 pts', '41 pts', '59 pts', '71 pts', '95 pts', '113 pts', '131 pts'], loc='best')
plt.xlabel(r'$\lambda$')
plt.ylabel(r'$\sigma_{11}$')
plt.title('Equal force model UTT - lambda_b_crit = 1.05 and N=45')
plt.tight_layout()
plt.savefig('cauchy_11_eq_force_P_tilde_modLog105_N45.pdf', transparent=True)
plt.close()
