function dict = importfile1(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   DICT = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   DICT = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   dict = importfile1('dict.txt', 1, 60);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/02/24 21:06:48

%% Initialize variables.
delimiter = {'\t',','};
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Create output variable
dict = table;
dict.VarName1 = cell2mat(raw(:, 1));
dict.VarName2 = cell2mat(raw(:, 2));
dict.VarName3 = cell2mat(raw(:, 3));
dict.VarName4 = cell2mat(raw(:, 4));
dict.VarName5 = cell2mat(raw(:, 5));
dict.VarName6 = cell2mat(raw(:, 6));
dict.VarName7 = cell2mat(raw(:, 7));
dict.VarName8 = cell2mat(raw(:, 8));
dict.VarName9 = cell2mat(raw(:, 9));
dict.VarName10 = cell2mat(raw(:, 10));
dict.VarName11 = cell2mat(raw(:, 11));
dict.VarName12 = cell2mat(raw(:, 12));
dict.VarName13 = cell2mat(raw(:, 13));
dict.VarName14 = cell2mat(raw(:, 14));
dict.VarName15 = cell2mat(raw(:, 15));
dict.VarName16 = cell2mat(raw(:, 16));
dict.VarName17 = cell2mat(raw(:, 17));
dict.VarName18 = cell2mat(raw(:, 18));
dict.VarName19 = cell2mat(raw(:, 19));
dict.VarName20 = cell2mat(raw(:, 20));
dict.VarName21 = cell2mat(raw(:, 21));
dict.VarName22 = cell2mat(raw(:, 22));
dict.VarName23 = cell2mat(raw(:, 23));
dict.VarName24 = cell2mat(raw(:, 24));
dict.VarName25 = cell2mat(raw(:, 25));
dict.VarName26 = cell2mat(raw(:, 26));
dict.VarName27 = cell2mat(raw(:, 27));
dict.VarName28 = cell2mat(raw(:, 28));
dict.VarName29 = cell2mat(raw(:, 29));
dict.VarName30 = cell2mat(raw(:, 30));
dict.VarName31 = cell2mat(raw(:, 31));
dict.VarName32 = cell2mat(raw(:, 32));
dict.VarName33 = cell2mat(raw(:, 33));
dict.VarName34 = cell2mat(raw(:, 34));
dict.VarName35 = cell2mat(raw(:, 35));
dict.VarName36 = cell2mat(raw(:, 36));
dict.VarName37 = cell2mat(raw(:, 37));
dict.VarName38 = cell2mat(raw(:, 38));
dict.VarName39 = cell2mat(raw(:, 39));
dict.VarName40 = cell2mat(raw(:, 40));
dict.VarName41 = cell2mat(raw(:, 41));
dict.VarName42 = cell2mat(raw(:, 42));
dict.VarName43 = cell2mat(raw(:, 43));
dict.VarName44 = cell2mat(raw(:, 44));
dict.VarName45 = cell2mat(raw(:, 45));
dict.VarName46 = cell2mat(raw(:, 46));
dict.VarName47 = cell2mat(raw(:, 47));
dict.VarName48 = cell2mat(raw(:, 48));
dict.VarName49 = cell2mat(raw(:, 49));
dict.VarName50 = cell2mat(raw(:, 50));
dict.VarName51 = cell2mat(raw(:, 51));
dict.VarName52 = cell2mat(raw(:, 52));
dict.VarName53 = cell2mat(raw(:, 53));
dict.VarName54 = cell2mat(raw(:, 54));
dict.VarName55 = cell2mat(raw(:, 55));
dict.VarName56 = cell2mat(raw(:, 56));
dict.VarName57 = cell2mat(raw(:, 57));
dict.VarName58 = cell2mat(raw(:, 58));
dict.VarName59 = cell2mat(raw(:, 59));
dict.VarName60 = cell2mat(raw(:, 60));
dict.VarName61 = cell2mat(raw(:, 61));
dict.VarName62 = cell2mat(raw(:, 62));
dict.VarName63 = cell2mat(raw(:, 63));
dict.VarName64 = cell2mat(raw(:, 64));
dict.VarName65 = cell2mat(raw(:, 65));
dict.VarName66 = cell2mat(raw(:, 66));
dict.VarName67 = cell2mat(raw(:, 67));
dict.VarName68 = cell2mat(raw(:, 68));
dict.VarName69 = cell2mat(raw(:, 69));
dict.VarName70 = cell2mat(raw(:, 70));
dict.VarName71 = cell2mat(raw(:, 71));
dict.VarName72 = cell2mat(raw(:, 72));
dict.VarName73 = cell2mat(raw(:, 73));
dict.VarName74 = cell2mat(raw(:, 74));
dict.VarName75 = cell2mat(raw(:, 75));
dict.VarName76 = cell2mat(raw(:, 76));
dict.VarName77 = cell2mat(raw(:, 77));
dict.VarName78 = cell2mat(raw(:, 78));
dict.VarName79 = cell2mat(raw(:, 79));

